#include "stdafx.h"
#include "OpenGL.h"

#ifdef RSX_GLES

#include "Emu/RSX/Program/GLSLTypes.h"

//
// ARMSX3: retarget RPCS3's generated GLSL at OpenGL ES.
//
// RPCS3 builds every shader at runtime, so this is a code-generation problem,
// not a matter of editing .glsl files. There are three emitters (GLVertexProgram,
// GLFragmentProgram, GLShaderInterpreter) plus a dozen fixed snippets that are
// shared verbatim with the Vulkan backend. Rather than fork all of them, the
// rewrite happens at the single point every shader passes through on its way to
// glShaderSource: gl::glsl::shader::precompile(). That function already has a
// precedent for exactly this - patch_macros_INTEL, a driver workaround applied to
// the finished source - so the hook costs upstream three guarded lines.
//
// What this does:
//   * rewrites the #version directive to "320 es"
//   * enables the ES extensions the generated code depends on
//   * emits the default precision qualifiers ES requires and desktop GL does not
//
// What this does NOT do, and why it is called out rather than papered over:
//
//   * sampler1D. ES has no 1D texture of any kind. The API side is emulated
//     (height-1 2D, see OpenGL_ES.cpp) but the shader side needs the decompilers
//     in Emu/RSX/Program to emit sampler2D and pad the coordinate, and that code
//     is shared with the Vulkan backend. Programs that sample a 1D texture will
//     fail to compile until that is done.
//
//   * gl_ClipDistance needs EXT_clip_cull_distance, which is enabled below but is
//     not universal on mobile. Where it is missing, user clip planes are lost.
//
//   * The MSAA sampler paths assume desktop sample-count introspection
//     (ARB_shader_texture_image_samples). capabilities.cpp reports that
//     unsupported, so multisampled programs are not generated in the first place.
//

namespace gl::es
{
	namespace
	{
		// Enabled, not required: most of these are core in ES 3.2, and demanding
		// an extension a compiler has folded into core is itself an error on some
		// drivers. "enable" is the spelling that works in both cases.
		constexpr const char* k_extensions =
			"#extension GL_EXT_texture_buffer : enable\n"                     // usamplerBuffer - the vertex stream
			"#extension GL_EXT_texture_cube_map_array : enable\n"
			"#extension GL_EXT_clip_cull_distance : enable\n"                 // gl_ClipDistance - user clip planes
			"#extension GL_EXT_shader_io_blocks : enable\n"
			"#extension GL_OES_texture_storage_multisample_2d_array : enable\n"
			"#extension GL_EXT_shader_framebuffer_fetch : enable\n";          // closest thing ES has to a texture barrier

		// ES has no default precision for float in fragment shaders, and none at
		// all for most opaque types. Omitting any one of these is a compile error
		// in the shader that happens to use it, so the block is exhaustive rather
		// than minimal - the compiler discards the unused ones.
		constexpr const char* k_precision =
			"precision highp float;\n"
			"precision highp int;\n"
			"precision highp sampler2D;\n"
			"precision highp sampler3D;\n"
			"precision highp samplerCube;\n"
			"precision highp sampler2DArray;\n"
			"precision highp sampler2DShadow;\n"
			"precision highp samplerCubeShadow;\n"
			"precision highp sampler2DArrayShadow;\n"
			"precision highp isampler2D;\n"
			"precision highp isampler3D;\n"
			"precision highp isamplerCube;\n"
			"precision highp isampler2DArray;\n"
			"precision highp usampler2D;\n"
			"precision highp usampler3D;\n"
			"precision highp usamplerCube;\n"
			"precision highp usampler2DArray;\n"
			"precision highp samplerBuffer;\n"
			"precision highp isamplerBuffer;\n"
			"precision highp usamplerBuffer;\n"
			"precision highp sampler2DMS;\n"
			"precision highp isampler2DMS;\n"
			"precision highp usampler2DMS;\n"
			"precision highp image2D;\n"
			"precision highp iimage2D;\n"
			"precision highp uimage2D;\n"
			"precision highp image3D;\n"
			"precision highp uimage3D;\n"
			"precision highp image2DArray;\n"
			"precision highp uimage2DArray;\n"
			"precision highp imageCube;\n"
			"precision highp uimageCube;\n";
	}

	void patch_glsl_for_es(std::string& source)
	{
		// The #version directive has to stay the first thing in the file, so find
		// the existing one and replace the whole line rather than prepending.
		const auto version_pos = source.find("#version");
		if (version_pos == std::string::npos)
		{
			// Nothing generated by RPCS3 is versionless; if that changes, an ES
			// compiler would silently fall back to ESSL 1.00 and produce a wall of
			// unrelated errors. Say what actually happened.
			rsx_log.error("GLES: shader source has no #version directive; it cannot be retargeted at ES.");
			return;
		}

		auto line_end = source.find('\n', version_pos);
		if (line_end == std::string::npos)
		{
			line_end = source.length();
		}
		else
		{
			line_end += 1;
		}

		std::string header = "#version 320 es\n";
		header += k_extensions;
		header += k_precision;

		source.replace(version_pos, line_end - version_pos, header);
	}
}

#endif // RSX_GLES
