#!/usr/bin/env python3
"""Synchronize ARMSX3 Android and Qt translation catalogs."""

from __future__ import annotations

import argparse
import copy
import json
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ANDROID_RES_DIRS = (
    ROOT / "android/armsx3-app/app/src/main/res",
    ROOT / "android/armsx3-ui/app/src/main/res",
)
QT_TRANSLATIONS = ROOT / "translations/qt"
QT_OUTPUT = ROOT / "bin/translations"
LANGUAGE_LIST = QT_OUTPUT / "languages.txt"
LANGUAGE_MANIFEST = ROOT / "translations/languages.json"
UI_I18N = ROOT / "android/armsx3-ui/app/src/main/assets/i18n"
GENERATED_KOTLIN = ROOT / "android/armsx3-ui/app/src/main/java/com/armsx2/i18n/GeneratedLanguages.kt"
UI_EN_SOURCE = ROOT / "android/armsx3-ui/app/src/main/java/com/armsx2/i18n/I18n.kt"
PLACEHOLDER_RE = re.compile(r"%(?:\d+\$)?[-#+0,(]*\d*(?:\.\d+)?[sdf]")
BARE_POSITIONAL_PLACEHOLDER_RE = re.compile(r"%[1-9](?![\d$sdf])")
KOTLIN_MAP_RE = re.compile(
    r"val\s+EN:\s*Map<String,\s*String>\s*=\s*mapOf\(\s*\n(?P<body>.*?)^\)",
    re.MULTILINE | re.DOTALL,
)
KOTLIN_ENTRY_RE = re.compile(
    r'^\s*(?P<key>"(?:\\.|[^"\\])*")\s+to\s+'
    r'(?P<value>"(?:\\.|[^"\\])*")\s*,?\s*$',
    re.MULTILINE,
)


def language_metadata() -> list[dict[str, object]]:
    if not LANGUAGE_MANIFEST.is_file():
        raise RuntimeError(f"Language manifest not found: {LANGUAGE_MANIFEST}")
    data = json.loads(LANGUAGE_MANIFEST.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise RuntimeError("Language manifest root must be an array")
    required = {"code", "english_name", "native_name"}
    codes: set[str] = set()
    for index, entry in enumerate(data):
        if not isinstance(entry, dict) or not required.issubset(entry):
            raise RuntimeError(f"Invalid language manifest entry at index {index}")
        code = str(entry["code"])
        if code in codes:
            raise RuntimeError(f"Duplicate language code: {code}")
        codes.add(code)
    return data


def languages() -> list[str]:
    return [str(entry["code"]) for entry in language_metadata()]


def kotlin_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False).replace("$", "\\$")


def generated_language_files() -> tuple[bytes, bytes]:
    metadata = language_metadata()
    language_text = "".join(f"{entry['code']}\n" for entry in metadata).encode()
    lines = [
        "// Generated by tools/update_translations.py. Do not edit manually.\n",
        "package com.armsx2.i18n\n\n",
        "internal val GENERATED_APP_LANGUAGES: List<AppLanguage> = listOf(\n",
    ]
    for entry in metadata:
        rtl = ", rtl = true" if entry.get("rtl", False) else ""
        lines.append(
            f"    AppLanguage({kotlin_string(entry['code'])}, "
            f"{kotlin_string(entry['english_name'])}, {kotlin_string(entry['native_name'])}{rtl}),\n"
        )
    lines.append(")\n")
    return language_text, "".join(lines).encode("utf-8")


def update_generated_language_files(check: bool) -> tuple[int, int]:
    changed = 0
    for path, desired in zip((LANGUAGE_LIST, GENERATED_KOTLIN), generated_language_files()):
        current = path.read_bytes() if path.is_file() else b""
        if current == desired:
            continue
        changed += 1
        if check:
            print(f"outdated: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(desired)
            print(f"generated: {path.relative_to(ROOT)}")
    return changed, 0


def android_qualifier(language: str) -> str:
    # Android uses a BCP-47 qualifier for numeric regions and modern Serbia.
    if language == "es-419":
        return "b+es+419"
    if language == "sr-SP":
        return "sr-rRS"
    parts = language.split("-", 1)
    return parts[0] if len(parts) == 1 else f"{parts[0]}-r{parts[1]}"


def parse_xml(path: Path) -> ET.ElementTree:
    parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))
    return ET.parse(path, parser=parser)


def resource_key(element: ET.Element) -> tuple[str, str] | None:
    name = element.get("name")
    return (element.tag, name) if isinstance(element.tag, str) and name else None


def placeholders(element: ET.Element) -> list[str]:
    return sorted(PLACEHOLDER_RE.findall("".join(element.itertext())))


def text_placeholders(value: str) -> list[str]:
    """Return Android/Compose formatting tokens used by a localized string."""
    return sorted(PLACEHOLDER_RE.findall(value) + BARE_POSITIONAL_PLACEHOLDER_RE.findall(value))


def canonical_ui_strings() -> dict[str, str]:
    """Extract the canonical Compose localization map from I18n.kt."""
    if not UI_EN_SOURCE.is_file():
        raise RuntimeError(f"Canonical Android UI strings not found: {UI_EN_SOURCE}")
    source = UI_EN_SOURCE.read_text(encoding="utf-8")
    map_match = KOTLIN_MAP_RE.search(source)
    if not map_match:
        raise RuntimeError(f"Could not find the EN map in {UI_EN_SOURCE.relative_to(ROOT)}")

    strings: dict[str, str] = {}
    for match in KOTLIN_ENTRY_RE.finditer(map_match.group("body")):
        key = json.loads(match.group("key"))
        value = json.loads(match.group("value"))
        # Kotlin's mapOf keeps the last value when a key appears more than once.
        strings[key] = value
    if not strings:
        raise RuntimeError(f"No canonical Android UI strings found in {UI_EN_SOURCE.relative_to(ROOT)}")
    return strings


def synchronized_android_tree(source: Path, target: Path) -> tuple[ET.ElementTree, list[str]]:
    source_root = parse_xml(source).getroot()
    target_root = parse_xml(target).getroot() if target.is_file() else ET.Element("resources")
    translated = {
        key: element
        for element in target_root
        if (key := resource_key(element)) is not None
    }
    errors: list[str] = []
    result = ET.Element("resources", source_root.attrib)

    for source_element in source_root:
        key = resource_key(source_element)
        if key is None:
            result.append(copy.deepcopy(source_element))
            continue
        selected = translated.get(key, source_element)
        if placeholders(selected) != placeholders(source_element):
            errors.append(
                f"{target.relative_to(ROOT)}: {key[1]} has incompatible placeholders "
                f"{placeholders(selected)} (expected {placeholders(source_element)})"
            )
        result.append(copy.deepcopy(selected))

    ET.indent(result, space="    ")
    return ET.ElementTree(result), errors


def tree_bytes(tree: ET.ElementTree) -> bytes:
    with tempfile.SpooledTemporaryFile() as stream:
        tree.write(stream, encoding="utf-8", xml_declaration=True)
        stream.seek(0)
        return stream.read() + b"\n"


def update_android(check: bool) -> tuple[int, int]:
    changed = 0
    failures = 0
    for resource_dir in ANDROID_RES_DIRS:
        source = resource_dir / "values/strings.xml"
        if not source.is_file():
            continue
        for language in languages():
            target = resource_dir / f"values-{android_qualifier(language)}/strings.xml"
            tree, errors = synchronized_android_tree(source, target)
            for error in errors:
                print(f"error: {error}", file=sys.stderr)
            failures += len(errors)
            desired = tree_bytes(tree)
            current = target.read_bytes() if target.is_file() else b""
            if current != desired:
                changed += 1
                if check:
                    print(f"outdated: {target.relative_to(ROOT)}")
                else:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_bytes(desired)
                    print(f"updated: {target.relative_to(ROOT)}")
    json_changed, json_failures = update_ui_json(check)
    return changed + json_changed, failures + json_failures


def update_ui_json(check: bool) -> tuple[int, int]:
    """Validate picker catalogs and enforce coverage for completed locales.

    Missing keys deliberately remain absent: I18n.kt falls back to its canonical
    English map, which makes an untranslated key distinguishable from a real
    translation and avoids copying stale English into every catalog. Locales
    marked ``complete`` in languages.json must mirror the full canonical key set.
    """
    changed = 0
    failures = 0
    canonical = canonical_ui_strings()
    if not check:
        UI_I18N.mkdir(parents=True, exist_ok=True)
    for metadata in language_metadata():
        language = str(metadata["code"])
        if language == "en":
            continue
        target = UI_I18N / f"{language}.json"
        if target.is_file():
            try:
                data = json.loads(target.read_text(encoding="utf-8"))
                if not isinstance(data, dict):
                    raise ValueError("catalog root must be an object")
            except (OSError, ValueError, json.JSONDecodeError) as error:
                print(f"error: {target.relative_to(ROOT)}: {error}", file=sys.stderr)
                failures += 1
                continue

            for key in sorted(canonical.keys() & data.keys()):
                value = data[key]
                if not isinstance(value, str):
                    print(f"error: {target.relative_to(ROOT)}: {key} must be a string", file=sys.stderr)
                    failures += 1
                    continue
                expected = text_placeholders(canonical[key])
                actual = text_placeholders(value)
                if actual != expected:
                    print(
                        f"error: {target.relative_to(ROOT)}: {key} has incompatible placeholders "
                        f"{actual} (expected {expected})",
                        file=sys.stderr,
                    )
                    failures += 1

            if metadata.get("complete", False):
                missing = sorted(canonical.keys() - data.keys())
                unexpected = sorted(data.keys() - canonical.keys())
                for key in missing:
                    print(f"error: {target.relative_to(ROOT)}: missing canonical key {key}", file=sys.stderr)
                for key in unexpected:
                    print(f"error: {target.relative_to(ROOT)}: unknown key {key}", file=sys.stderr)
                failures += len(missing) + len(unexpected)
            continue
        changed += 1
        if check:
            print(f"missing: {target.relative_to(ROOT)}")
            continue
        data = {"_note": f"Untranslated ({language}); missing keys fall back to English."}
        target.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"created: {target.relative_to(ROOT)}")
    return changed, failures


def qt_tool(name: str) -> str | None:
    for candidate in (f"{name}6", name):
        if path := shutil.which(candidate):
            return path
    for candidate in Path("/usr").glob(f"**/{name}"):
        if candidate.is_file() and candidate.stat().st_mode & 0o111:
            return str(candidate)
    return None


def update_qt(check: bool, required: bool = False) -> tuple[int, int]:
    lupdate = qt_tool("lupdate")
    lrelease = qt_tool("lrelease")
    if not lupdate or not lrelease:
        missing = ", ".join(name for name, path in (("lupdate", lupdate), ("lrelease", lrelease)) if not path)
        level = "error" if required else "warning"
        print(f"{level}: Qt Linguist tool(s) not found: {missing}", file=sys.stderr)
        print("Install the Qt 6 Linguist tools to update TS/QM catalogs.", file=sys.stderr)
        return (0, 1) if required else (0, 0)

    QT_TRANSLATIONS.mkdir(parents=True, exist_ok=True)
    QT_OUTPUT.mkdir(parents=True, exist_ok=True)
    catalogs = [QT_TRANSLATIONS / f"rpcs3_{language.replace('-', '_')}.ts" for language in languages()]
    command = [lupdate, "-recursive", str(ROOT / "rpcs3"), "-ts", *(str(path) for path in catalogs)]
    if check:
        with tempfile.TemporaryDirectory() as directory:
            temporary = [Path(directory) / path.name for path in catalogs]
            subprocess.run([*command[:4], *(str(path) for path in temporary)], check=True)
            changed = sum(not original.is_file() or original.read_bytes() != candidate.read_bytes()
                          for original, candidate in zip(catalogs, temporary))
            for original, candidate in zip(catalogs, temporary):
                if not original.is_file() or original.read_bytes() != candidate.read_bytes():
                    print(f"outdated: {original.relative_to(ROOT)}")
            return changed, 0

    subprocess.run(command, check=True)
    for language, catalog in zip(languages(), catalogs):
        tree = parse_xml(catalog)
        tree.getroot().set("language", language.replace("-", "_"))
        tree.write(catalog, encoding="utf-8", xml_declaration=True)
        output = QT_OUTPUT / f"rpcs3_{language.replace('-', '_')}.qm"
        subprocess.run([lrelease, str(catalog), "-qm", str(output)], check=True)
    return len(catalogs), 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument("--android", action="store_true", help="update Android resources only")
    selection.add_argument("--qt", action="store_true", help="update Qt TS/QM catalogs only")
    parser.add_argument("--check", action="store_true", help="report outdated files without changing them")
    args = parser.parse_args()

    run_android = args.android or not args.qt
    run_qt = args.qt or not args.android
    changed = failures = 0
    try:
        count, errors = update_generated_language_files(args.check)
        changed += count
        failures += errors
        if run_android:
            count, errors = update_android(args.check)
            changed += count
            failures += errors
        if run_qt:
            count, errors = update_qt(args.check, required=args.qt)
            changed += count
            failures += errors
    except (OSError, ET.ParseError, subprocess.CalledProcessError, RuntimeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if args.check and changed:
        print(f"{changed} translation file(s) need updating.")
        return 1
    if failures:
        return 1
    print("Translations are up to date." if args.check else "Translations updated successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
